# Generated by Django 5.1.3 on 2024-11-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SOCIO', 'Socio')], default='SOCIO', max_length=10, verbose_name='Rol del usuario'),
        ),
    ]
