# Generated by Django 5.1.3 on 2024-11-25 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('LIC', 'Licencia'), ('TAR', 'Tarjeta de Propiedad'), ('OTR', 'Otros')], max_length=3, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Documento de Socio',
                'verbose_name_plural': 'Documentos de Socios',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
