# Generated by Django 5.1.3 on 2024-11-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_documentosocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocio',
            name='archivo',
            field=models.FileField(upload_to='documentos_socios/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentosocio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio', verbose_name='Socio'),
        ),
    ]
